# Generated by Django 5.0.4 on 2025-06-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createShift", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedshift",
            name="end_time",
            field=models.TimeField(default="17:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignedshift",
            name="start_time",
            field=models.TimeField(default="7:00"),
            preserve_default=False,
        ),
    ]
