# Generated by Django 5.0.4 on 2025-06-26 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createShift", "0002_assignedshift_end_time_assignedshift_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedshift",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignedshift_set",
                to="createShift.shift",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="week",
            unique_together={("start_date", "end_date")},
        ),
    ]
