# Generated by Django 5.0.4 on 2025-07-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createShift", "0003_alter_assignedshift_shift_alter_week_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="line_user_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
